labels:
  app: estafette-cloudflare-dns
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/estafette/estafette-cloudflare-dns
    commands:
    - go test ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/estafette-cloudflare-dns .

  bake:
    image: docker:17.03.0-ce
    commands:
    - cp Dockerfile ./publish
    - docker build -t estafette-cloudflare-dns ./publish