apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: estafette-cloudflare-dns
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - services
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]