{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    {{- if (.Values.teamName) }}
    team: {{ .Values.teamName }}
    {{- end}}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - services
  verbs:
  - list
  - watch
  - update
- apiGroups: ["extensions"]
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - update
{{- end }}