apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    {{- if (.Values.teamName) }}
    team: {{ .Values.teamName }}
    {{- end}}