
image:
  repository: estafette/estafette-cloudflare-dns
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 15Mi

rbac:
  # If true, create & use RBAC resources
  create: false

revisionHistoryLimit: 10

cloudflareApiKey: ABC
cloudflareApiEmail: a@server.com

livenessProbe:
  path: /metrics
  port: 9101
  initialDelaySeconds: 30
  timeoutSeconds: 1

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9101"

extraLabels: {}
  # team: tooling